sudo: required
language: bash
branches:
  only:
    - master
services:
  - docker

install:
  - echo $HOST_ADDRESS
  - echo $HOST_ADDRESS >> $HOME/.ssh/known_hosts

script:
  - docker-compose -f docker-compose.yml build && docker-compose run --rm web bash -c "black . && python wait_for_postgres.py &&
    ./manage.py test"
after_success:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && bash deploy/deploy-script.sh || exit 0'
