# version: "3"

# services:
#   web:
#     restart: always
#     env_file:
#       - ./deploy/.prod.env
#     image: web
#     build: ./
#     command: >
#       bash -c "
#                python ./manage.py makemigrations &&
#                python ./manage.py migrate &&
#                python ./manage.py collectstatic --noinput &&
#                gunicorn --bind 0.0.0.0:8000 --access-logfile - cvalki.wsgi:application"
#     volumes:
#       - ./:/code
#     networks:
#       - nginx_network

#   nginx:
#     build: ./nginx
#     ports:
#       - 80:80
#       - 443:443
#     depends_on:
#       - web
#       - certbot
#     networks:
#       - nginx_network
#     volumes:
#       - ./data/certbot/conf:/etc/letsencrypt
#       - ./data/certbot/www:/var/www/certbot

#   certbot:
#     image: certbot/certbot
#     networks:
#       - nginx_network
#     volumes:
#       - ./data/certbot/conf:/etc/letsencrypt
#       - ./data/certbot/www:/var/www/certbot

# networks:
#   nginx_network:
#     driver: bridge
